"""add_auth0_fields_to_user

Revision ID: 0af355c4e651
Revises: 
Create Date: 2026-01-04 12:08:57.883219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0af355c4e651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('role',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System roles cannot be deleted'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_code'), ['code'], unique=True)

    op.create_table('user',
    sa.Column('auth0_id', sa.String(length=100), nullable=True, comment='Auth0 user ID (sub claim)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Nullable for Auth0 users'),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth0_id'), ['auth0_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('asset',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique code within organization (e.g., SITE-001, BLK-A, FLR-01, UNIT-101)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=12, scale=2), nullable=True, comment='Area in square meters'),
    sa.Column('floor_number', sa.Integer(), nullable=True, comment='Floor number (for floor/unit types)'),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional asset-specific metadata'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_asset_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['asset.id'], name=op.f('fk_asset_parent_id_asset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_asset_org_code')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_code'), ['code'], unique=False)
        batch_op.create_index('ix_asset_hierarchy', ['organization_id', 'parent_id', 'asset_type'], unique=False)
        batch_op.create_index('ix_asset_org_type', ['organization_id', 'asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_asset_parent', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_parent_id'), ['parent_id'], unique=False)

    op.create_table('invoice',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Invoice line items as JSON array'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_invoice_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice')),
    sa.UniqueConstraint('organization_id', 'invoice_number', name='uq_invoice_number')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_due_date', ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index('ix_invoice_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('organization_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Default organization for user'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_user_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_organization_user_role_id_role'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_organization_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_user')),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_user')
    )
    with op.batch_alter_table('organization_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_user_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_user_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_user_user_id'), ['user_id'], unique=False)

    op.create_table('wallet',
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True, comment='Maximum negative balance allowed'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_wallet_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet')),
    sa.UniqueConstraint('organization_id', 'currency', name='uq_wallet_org_currency')
    )
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_org', ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_organization_id'), ['organization_id'], unique=False)

    op.create_table('gateway',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('mqtt_client_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_gateway_asset_id_asset'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_gateway_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway')),
    sa.UniqueConstraint('mqtt_client_id', name=op.f('uq_gateway_mqtt_client_id')),
    sa.UniqueConstraint('organization_id', 'serial_number', name='uq_gateway_serial')
    )
    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateway_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_gateway_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_status'), ['status'], unique=False)

    op.create_table('lease',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_email', sa.String(length=255), nullable=True),
    sa.Column('tenant_phone', sa.String(length=50), nullable=True),
    sa.Column('tenant_id_number', sa.String(length=50), nullable=True, comment='National ID or passport number'),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_lease_asset_id_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_lease_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lease')),
    sa.UniqueConstraint('contract_number', name=op.f('uq_lease_contract_number'))
    )
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_lease_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_lease_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_status'), ['status'], unique=False)

    op.create_table('transaction',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True, comment='External reference (e.g., payment gateway ID)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_transaction_invoice_id_invoice'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('fk_transaction_wallet_id_wallet'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index('ix_transaction_type', ['transaction_type'], unique=False)
        batch_op.create_index('ix_transaction_wallet', ['wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('device',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False, comment='Unique device identifier (e.g., MAC, serial)'),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Device-specific configuration'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_device_asset_id_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], name=op.f('fk_device_gateway_id_gateway'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_device_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('organization_id', 'device_id', name='uq_device_id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index('ix_device_asset', ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_gateway_id'), ['gateway_id'], unique=False)
        batch_op.create_index('ix_device_org_type', ['organization_id', 'device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_status'), ['status'], unique=False)

    op.create_table('telemetry_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False, comment='e.g., voltage, current, power, temperature, humidity'),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='e.g., V, A, W, kWh, °C, %'),
    sa.Column('quality', sa.Integer(), nullable=False, comment='Data quality 0-100'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_telemetry_data_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_data'))
    )
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_data_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_data_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_data_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_telemetry_device_time', ['device_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_telemetry_metric', ['metric_name', 'timestamp'], unique=False)
        batch_op.create_index('ix_telemetry_time', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_data', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_time')
        batch_op.drop_index('ix_telemetry_metric')
        batch_op.drop_index('ix_telemetry_device_time')
        batch_op.drop_index(batch_op.f('ix_telemetry_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_data_metric_name'))
        batch_op.drop_index(batch_op.f('ix_telemetry_data_device_id'))

    op.drop_table('telemetry_data')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_status'))
        batch_op.drop_index(batch_op.f('ix_device_organization_id'))
        batch_op.drop_index('ix_device_org_type')
        batch_op.drop_index(batch_op.f('ix_device_gateway_id'))
        batch_op.drop_index(batch_op.f('ix_device_device_type'))
        batch_op.drop_index(batch_op.f('ix_device_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_asset_id'))
        batch_op.drop_index('ix_device_asset')

    op.drop_table('device')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_wallet_id'))
        batch_op.drop_index('ix_transaction_wallet')
        batch_op.drop_index('ix_transaction_type')
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_type'))
        batch_op.drop_index('ix_transaction_created')

    op.drop_table('transaction')
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_status'))
        batch_op.drop_index(batch_op.f('ix_lease_organization_id'))
        batch_op.drop_index('ix_lease_org_status')
        batch_op.drop_index('ix_lease_dates')
        batch_op.drop_index(batch_op.f('ix_lease_asset_id'))

    op.drop_table('lease')
    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateway_status'))
        batch_op.drop_index(batch_op.f('ix_gateway_serial_number'))
        batch_op.drop_index(batch_op.f('ix_gateway_organization_id'))
        batch_op.drop_index('ix_gateway_org_status')
        batch_op.drop_index(batch_op.f('ix_gateway_asset_id'))

    op.drop_table('gateway')
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_organization_id'))
        batch_op.drop_index('ix_wallet_org')

    op.drop_table('wallet')
    with op.batch_alter_table('organization_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_organization_user_organization_id'))

    op.drop_table('organization_user')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_organization_id'))
        batch_op.drop_index('ix_invoice_org_status')
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index('ix_invoice_due_date')

    op.drop_table('invoice')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_parent_id'))
        batch_op.drop_index('ix_asset_parent')
        batch_op.drop_index(batch_op.f('ix_asset_organization_id'))
        batch_op.drop_index('ix_asset_org_type')
        batch_op.drop_index('ix_asset_hierarchy')
        batch_op.drop_index(batch_op.f('ix_asset_code'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_type'))

    op.drop_table('asset')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_auth0_id'))

    op.drop_table('user')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_code'))

    op.drop_table('role')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    # ### end Alembic commands ###
