"""Add notification tables

Revision ID: 75790e51fe08
Revises: 0af355c4e651
Create Date: 2026-01-04 14:27:39.686367

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '75790e51fe08'
down_revision: str | None = '0af355c4e651'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
