"""add distance estimate fields

Revision ID: 3aed16769115
Revises: 7b3b32bd391d
Create Date: 2025-12-02 06:16:16.518489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aed16769115'
down_revision = '7b3b32bd391d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_estimate', sa.Float(), nullable=True))

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_estimate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('distance_estimate')

    with op.batch_alter_table('discovery_queue', schema=None) as batch_op:
        batch_op.drop_column('distance_estimate')

    # ### end Alembic commands ###
