"""Add Wallet WalletTransaction and update Notification

Revision ID: 51bbc955cba2
Revises: 3aed16769115
Create Date: 2025-12-06 15:18:38.155550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51bbc955cba2'
down_revision = '3aed16769115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data')
        batch_op.drop_column('reference_type')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('is_read')
        batch_op.drop_column('type')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
