"""Add VPP and Energy models

Revision ID: 7b3b32bd391d
Revises: 
Create Date: 2025-12-01 14:44:07.380194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b3b32bd391d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.drop_column('is_online')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('node_address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('battery_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('signal_strength', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('capacity_info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('site_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sites_site_type'), ['site_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_site_type'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('site_type')
        batch_op.drop_column('district')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('capacity_info')
        batch_op.drop_column('model_number')
        batch_op.drop_column('brand')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('signal_strength')
        batch_op.drop_column('battery_level')
        batch_op.drop_column('node_address')
        batch_op.drop_column('protocol')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
