"""Add created_by to Automation, add AuditLog model

Revision ID: f982c9a1e34c
Revises: 51bbc955cba2
Create Date: 2025-12-07 13:06:06.853280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f982c9a1e34c'
down_revision = '51bbc955cba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
