"""
Marketplace Module - Database Models

Maintenance and service marketplace:
- Alarm: Device/system alerts that may require attention
- Job: Maintenance/repair job requests
- JobOffer: Operator bids on jobs
- JobProof: Verification of job completion
"""
import uuid
from datetime import datetime
from decimal import Decimal
from enum import Enum

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.core.models import Base


class AlarmSeverity(str, Enum):
    """Alarm severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlarmStatus(str, Enum):
    """Alarm status."""
    OPEN = "open"
    ACKNOWLEDGED = "ack"
    CLOSED = "closed"


class JobCategory(str, Enum):
    """Job categories for maintenance."""
    PLUMBING = "plumbing"
    ELECTRICAL = "electrical"
    HVAC = "hvac"
    APPLIANCE = "appliance"
    GENERAL = "general"
    SECURITY = "security"
    CLEANING = "cleaning"


class JobStatus(str, Enum):
    """Job lifecycle status."""
    OPEN = "open"
    OFFERED = "offered"
    ASSIGNED = "assigned"
    IN_PROGRESS = "in_progress"
    DONE = "done"
    CANCELLED = "cancelled"


class JobOfferStatus(str, Enum):
    """Job offer status."""
    OFFERED = "offered"
    WITHDRAWN = "withdrawn"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


class JobProofType(str, Enum):
    """Types of job completion proof."""
    GATEWAY_QR = "gateway_qr"
    PHOTO = "photo"
    DEVICE_OK = "device_ok"
    SIGNATURE = "signature"


class Alarm(Base):
    """
    System/device alarms.
    
    Generated by:
    - Device anomaly detection
    - Predictive maintenance
    - Manual reports
    
    Can trigger job creation.
    """
    __tablename__ = "alarm"
    
    __table_args__ = (
        Index("idx_alarm_asset", "asset_id"),
        Index("idx_alarm_status", "status"),
        Index("idx_alarm_severity", "severity"),
    )
    
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("asset.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    device_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("device.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )
    
    message: Mapped[str] = mapped_column(Text, nullable=False)
    
    status: Mapped[str] = mapped_column(
        String(20),
        default=AlarmStatus.OPEN.value,
        nullable=False,
        index=True,
    )
    
    # Additional context
    metadata_: Mapped[dict | None] = mapped_column(
        "metadata",
        JSONB,
        nullable=True,
        default=dict,
    )
    
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    acknowledged_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )


class Job(Base):
    """
    Maintenance/repair job.
    
    Created from alarms or manual requests.
    Operators can bid on jobs.
    """
    __tablename__ = "job"
    
    __table_args__ = (
        Index("idx_job_asset", "asset_id"),
        Index("idx_job_status", "status"),
        Index("idx_job_category", "category"),
    )
    
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("asset.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    # Related alarm (optional)
    alarm_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("alarm.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    category: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        index=True,
    )
    
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    urgency: Mapped[str] = mapped_column(
        String(20),
        default="normal",
        nullable=False,
        comment="low/normal/high/urgent",
    )
    
    status: Mapped[str] = mapped_column(
        String(20),
        default=JobStatus.OPEN.value,
        nullable=False,
        index=True,
    )
    
    # Assigned operator
    assigned_operator_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    assigned_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    # Rating after completion
    rating: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="1-5 star rating",
    )
    
    rating_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Relationships
    offers: Mapped[list["JobOffer"]] = relationship(
        "JobOffer",
        back_populates="job",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    
    proofs: Mapped[list["JobProof"]] = relationship(
        "JobProof",
        back_populates="job",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class JobOffer(Base):
    """
    Operator bid on a job.
    
    Operators can submit price estimates and ETAs.
    Owner/tenant selects the winning offer.
    """
    __tablename__ = "job_offer"
    
    __table_args__ = (
        Index("idx_offer_job", "job_id"),
        Index("idx_offer_operator", "operator_user_id"),
        Index("idx_offer_status", "status"),
    )
    
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("job.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    operator_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    price_estimate: Mapped[Decimal | None] = mapped_column(
        Numeric(12, 2),
        nullable=True,
    )
    
    currency: Mapped[str] = mapped_column(
        String(3),
        default="TRY",
        nullable=False,
    )
    
    eta_minutes: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Estimated time of arrival in minutes",
    )
    
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    status: Mapped[str] = mapped_column(
        String(20),
        default=JobOfferStatus.OFFERED.value,
        nullable=False,
        index=True,
    )
    
    # Relationships
    job: Mapped["Job"] = relationship(
        "Job",
        back_populates="offers",
    )


class JobProof(Base):
    """
    Proof of job completion.
    
    Required for payment release and commission calculation.
    """
    __tablename__ = "job_proof"
    
    __table_args__ = (
        Index("idx_job_proof_job", "job_id"),
    )
    
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("job.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    proof_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        comment="gateway_qr/photo/device_ok/signature",
    )
    
    proof_payload: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Photo URLs, QR data, device status, etc.",
    )
    
    uploaded_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    # Relationships
    job: Mapped["Job"] = relationship(
        "Job",
        back_populates="proofs",
    )
